const groceries =
[
    { name: "Milk", price: "$3.49", type: "Dairy" },
    { name: "Bread", price: "$2.99", type: "Grain" },
    { name: "Eggs", price: "$4.29", type: "Protein" },
    { name: "1 lb Apples", price: "$1.49", type: "Produce" },
    { name: "1 lb Chicken Breast", price: "$6.99", type: "Protein" },
    { name: "Rice", price: "$2.99", type: "Grain" },
    { name: "Cheddar Cheese", price: "$5.49", type: "Dairy" },
    { name: "1 lb Bananas", price: "$0.59", type: "Produce" },
    { name: " 1 lb Tomatoes", price: "$2.49", type: "Produce" },
    { name: "1 lb Ground Beef", price: "$5.99", type: "Protein" },
    { name: "Butter", price: "$4.99", type: "Dairy" },
    { name: "Orange Juice", price: "$3.99", type: "Beverage" },
    { name: "Cereal", price: "$4.29", type: "Pantry" },
    { name: "1 lb Potatoes", price: "$1.99", type: "Produce" },
    { name: "Pasta", price: "$1.79", type: "Grain" },
    { name: "Olive Oil", price: "$7.99", type: "Pantry" },
    { name: "Yogurt", price: "$1.49", type: "Dairy" },
    { name: "1 lb Salmon", price: "$9.99", type: "Protein" },
    { name: "Coffee", price: "$8.99", type: "Beverage" },
    { name: "Lettuce", price: "$1.99", type: "Produce" },
    { name: "Cream Cheese", price: "$3.29", type: "Dairy" },
    { name: "Bagels", price: "$3.79", type: "Grain" },
    { name: "1 lb Turkey", price: "$7.99", type: "Protein" },
    { name: "1 lb Peaches", price: "$2.89", type: "Produce" },
    { name: "1 lb Carrots", price: "$1.49", type: "Produce" },
    { name: "Soda", price: "$1.49", type: "Beverage" },
    { name: "Sugar", price: "$2.49", type: "Pantry" },
    { name: "Mozzarella", price: "$4.49", type: "Dairy" },
    { name: "Quinoa", price: "$3.99", type: "Grain" },
    { name: "1 lb Pork Chops", price: "$5.99", type: "Protein" },
    { name: "Spinach", price: "$2.49", type: "Produce" },
    { name: "Almond Milk", price: "$3.49", type: "Beverage" },
    { name: "Flour", price: "$2.29", type: "Pantry" },
    { name: "Parmesan Cheese", price: "$6.49", type: "Dairy" },
    { name: "Whole Wheat Bread", price: "$3.29", type: "Grain" },
    { name: "Tofu", price: "$2.99", type: "Protein" },
    { name: "1 lb Bell Peppers", price: "$1.99", type: "Produce" },
    { name: "Cucumbers", price: "$0.89", type: "Produce" },
    { name: "Tea", price: "$4.49", type: "Beverage" },
    { name: "Honey", price: "$5.99", type: "Pantry" },
    { name: "Greek Yogurt", price: "$1.99", type: "Dairy" },
    { name: "Oats", price: "$3.29", type: "Grain" },
    { name: "1 lb Ham", price: "$6.99", type: "Protein" },
    { name: "Strawberries", price: "$3.49", type: "Produce" },
    { name: "Lemons", price: "$0.69", type: "Produce" },
    { name: "Iced Tea", price: "$2.49", type: "Beverage" },
    { name: "Ketchup", price: "$2.29", type: "Pantry" },
    { name: "Provolone Cheese", price: "$4.99", type: "Dairy" },
    { name: "Couscous", price: "$2.49", type: "Grain" },
    { name: "1 lb Bacon", price: "$7.49", type: "Protein" },
    { name: "Blueberries", price: "$3.99", type: "Produce" },
    { name: "Avocados", price: "$1.49", type: "Produce" },
    { name: "Lime Juice", price: "$1.99", type: "Beverage" },
    { name: "Soy Sauce", price: "$2.99", type: "Pantry" },
]

export {groceries}